{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qadash.fullname" . }}-uploads
  labels:
    {{- include "qadash.labels" . | nindent 4 }}
    app: uploads
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size | default "50Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qadash.fullname" . }}-reports
  labels:
    {{- include "qadash.labels" . | nindent 4 }}
    app: reports
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size | default "100Gi" }}
{{- end }}