FROM node:22-alpine AS development
RUN apk add --no-cache libc6-compat && npm config set fund false && npm config set audit false
WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/types/package.json ./packages/types/
COPY packages/utils/package.json ./packages/utils/
COPY packages/config/package.json ./packages/config/
COPY packages/logger/package.json ./packages/logger/
COPY apps/backend/package.json ./apps/backend/

RUN npm ci

EXPOSE 3001
ENV NODE_ENV=development
ENV PORT=3001

CMD ["npm", "run", "dev"]
