import { Injectable, Logger } from '@nestjs/common';
import OpenAI from 'openai';
import { ChatCompletionMessageParam } from 'openai/resources/chat/completions';

export interface GenerateDto {
  projectName: string;
  filesCount: number;
  options: {
    positive: boolean;
    negative: boolean;
    edge: boolean;
    security: boolean;
    browser: boolean;
    mobile: boolean;
  };
  customPrompt?: string;
}

@Injectable()
export class GeneratorService {
  private readonly logger = new Logger(GeneratorService.name);

  private async callAI(apiKey: string, baseURL: string, model: string, messages: ChatCompletionMessageParam[], temperature = 0.7) {
    const { default: OpenAI } = await import('openai');
    const client = new OpenAI({ apiKey, baseURL });
    const completion = await client.chat.completions.create({ model, messages, temperature });
    let text = completion.choices[0]?.message?.content || '{}';
    text = text.replace(/^```(?:json)?\s*|```$/gm, '').trim();
    try { return JSON.parse(text); } catch { return null; }
  }

  private async callAIWithFallback(apiKey: string, baseURL: string, systemPrompt: string, userPrompt: string, temperature = 0.7) {
    const messages: ChatCompletionMessageParam[] = [{ role: 'system', content: systemPrompt }, { role: 'user', content: userPrompt }];
    const models = [
      process.env.AI2_MODEL || 'openrouter/free',
      ...(process.env.AI2_FALLBACK_MODELS || '').split(',').map(m => m.trim()).filter(Boolean),
    ];
    for (const model of models) {
      this.logger.log(`AI#2 trying model: ${model}`);
      const result = await this.callAI(apiKey, baseURL, model, messages, temperature).catch(() => null);
      if (result) {
        this.logger.log(`AI#2 succeeded with model: ${model}`);
        return result;
      }
    }
    return null;
  }

  private async generateBatch(apiKey: string, baseURL: string, modelOrFallback: boolean, systemPrompt: string, userPrompt: string, batchSize: number, total: number): Promise<unknown[]> {
    const all = [];
    const seen = new Set();
    const batches = Math.ceil(total / batchSize);
    for (let b = 0; b < batches; b++) {
      const remaining = total - all.length;
      const count = Math.min(batchSize, remaining);
      this.logger.log(`Batch ${b + 1}/${batches}: generating ${count} test cases`);
      const prompt = `${systemPrompt}\nGenerate exactly ${count} test cases. Focus on scenarios not covered in previous batches.`;
      const result = modelOrFallback
        ? await this.callAIWithFallback(apiKey, baseURL, prompt, userPrompt).catch(() => null)
        : await this.callAI(apiKey, baseURL, process.env.AI_MODEL || 'gpt-4', [{ role: 'system', content: prompt } as ChatCompletionMessageParam, { role: 'user', content: userPrompt } as ChatCompletionMessageParam]).catch(() => null);
      if (result?.testCases) {
        for (const tc of result.testCases) {
          const key = tc.title?.toLowerCase().trim();
          if (key && !seen.has(key)) { seen.add(key); all.push(tc); }
        }
      }
      if (all.length >= total) break;
    }
    return all;
  }

  async generate(dto: GenerateDto) {
    this.logger.log(`Generating test cases from dual AI for: ${dto.projectName}`);

    const count = Math.max(dto.filesCount || 5, 1);
    const BATCH_SIZE = 50;

    const baseSystem = 'You are a senior QA engineer. Generate comprehensive, production-quality test cases in JSON format. Return an object with keys: projectName, summary, coverage (number), testCases (array of {id, module, feature, title, preconditions, steps, testData, expected, priority, severity, type, validation, automationCandidate, playwrightCode}).';
    const userPrompt = `Options: ${JSON.stringify(dto.options)}\nProject: ${dto.projectName || ''}\n${dto.customPrompt ? `Additional context: ${dto.customPrompt}` : ''}`;

    const [results1, results2] = await Promise.all([
      this.generateBatch(process.env.OPENAI_API_KEY, process.env.AI_BASE_URL || 'https://api.openai.com/v1', false, baseSystem, userPrompt, BATCH_SIZE, count),
      this.generateBatch(process.env.AI2_API_KEY, process.env.AI2_BASE_URL || 'https://openrouter.ai/api/v1', true, baseSystem, userPrompt, BATCH_SIZE, count),
    ]);

    const allTestCases: unknown[] = [];
    const seen = new Set();
    for (const tc of [...results1, ...results2]) {
      const typedTc = tc as { title?: string } | null;
      const key = typedTc?.title?.toLowerCase().trim();
      if (key && !seen.has(key)) { seen.add(key); allTestCases.push(tc); }
    }

    const finalTestCases = allTestCases.slice(0, count).map((tc, i) => ({ ...tc as Record<string, unknown>, id: `TC-${String(i + 1).padStart(3, '0')}` }));

    return {
      aiGenerated: true,
      requestedCount: count,
      projectName: dto.projectName || 'Generated',
      summary: `Test cases generated by dual AI in ${Math.ceil(count / BATCH_SIZE)} batch(es) per AI`,
      totalTestCases: finalTestCases.length,
      testCases: finalTestCases,
      sources: { groq: results1.length > 0, deepseek: results2.length > 0 },
    };
  }

  async runAction(action: string, data: unknown) {
    this.logger.log(`Running generator AI action with dual AI: ${action}`);

    const systemPrompts: Record<string, string> = {
      improve: 'Improve the following test cases: optimize preconditions, refine steps, and enhance validation assertions. Return JSON with success (bool), message, and refinedCount (number).',
      generate_missing: 'Analyze the following test cases and identify missing boundary/edge/negative scenarios. Return JSON with success (bool), message, and missingCases array.',
      rtm: 'Generate a Requirement Traceability Matrix for the following test cases. Return JSON with success (bool), message, and rtm array.',
    };

    const systemPrompt = systemPrompts[action] || `Execute action "${action}" on the given data and return JSON with success (bool) and message fields.`;

    const [result1, result2] = await Promise.all([
      this.callAI(
        process.env.OPENAI_API_KEY,
        process.env.AI_BASE_URL || 'https://api.openai.com/v1',
        process.env.AI_MODEL || 'gpt-4',
        [{ role: 'system', content: systemPrompt } as ChatCompletionMessageParam, { role: 'user', content: JSON.stringify(data) } as ChatCompletionMessageParam],
        0.3,
      ).catch(() => null),
      this.callAIWithFallback(
        process.env.AI2_API_KEY,
        process.env.AI2_BASE_URL || 'https://openrouter.ai/api/v1',
        systemPrompt,
        JSON.stringify(data),
        0.3,
      ).catch(() => null),
    ]);

      return result1 || result2 || { success: true, message: `Action ${action} completed` };
  }
}
